import {
  Bus,
  Briefcase,
  Car,
  Clapperboard,
  CreditCard,
  Droplets,
  Dumbbell,
  Gift,
  HeartPulse,
  Home,
  Landmark,
  Lightbulb,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingCart,
  Sparkles,
  Utensils,
  Wifi,
  LucideIcon,
} from 'lucide-react-native';

export const CAT_ICONS: Record<string, LucideIcon> = {
  auto: Car,
  casa: Home,
  comida: ShoppingCart,
  tel: Wifi,
  dep: Dumbbell,
  entr: Clapperboard,
  fact: Receipt,
  hig: Droplets,
  masc: PawPrint,
  reg: Gift,
  rest: Utensils,
  ropa: Shirt,
  salud: HeartPulse,
  transp: Bus,
  prest: Landmark,
  viajes: Plane,
  tarj: CreditCard,
  serv: Lightbulb,
  salario: Briefcase,
  ahorro: PiggyBank,
  extras: Sparkles,
};
